                            Calidad, Limpieza y Preparación de Datos

Paso 1 - Importar librerías

In [57]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

Paso 2 - Cargar el dataset

In [58]:
from google.colab import files

uploaded = files.upload()

Saving streaming_users_dirty.json to streaming_users_dirty (1).json

In [59]:
df = pd.read_json("streaming_users_dirty.json")

Paso 3 - Mostrar información genera

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8160 entries, 0 to 8159
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8160 non-null   int64
 1   age                       8160 non-null   int64
 2   subscription_plan         8160 non-null   object
 3   monthly_watch_time_mins   7967 non-null   float64
 4   country                   8160 non-null   object
 5   favorite_genre            7920 non-null   object
 6   last_login_date           7840 non-null   object
 7   customer_support_tickets  8160 non-null   int64
dtypes: float64(1), int64(3), object(4)
memory usage: 510.1+ KB

Paso 4 - Ver los primeros registros

In [61]:
df.head()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1

Paso 5 - Buscar valores nulos

In [62]:
df.isnull().sum()

user_id                       0
age                           0
subscription_plan             0
monthly_watch_time_mins     193
country                       0
favorite_genre              240
last_login_date             320
customer_support_tickets      0
dtype: int64

Paso 6 - Completar valores faltantes

In [63]:
for columna in df.select_dtypes(include=["int64","float64"]).columns:
    df[columna] = df[columna].fillna(df[columna].median())

In [64]:
for columna in df.select_dtypes(include="object").columns:
    df[columna] = df[columna].fillna(df[columna].mode()[0])

Paso 7 - Verificar que ya no existan nulos

In [65]:
df.isnull().sum()

user_id                     0
age                         0
subscription_plan           0
monthly_watch_time_mins     0
country                     0
favorite_genre              0
last_login_date             0
customer_support_tickets    0
dtype: int64

Paso 8 - Buscar registros duplicados

In [66]:
df.duplicated().sum()

np.int64(127)

Paso 9 - Eliminar registros duplicados

In [67]:
df = df.drop_duplicates()

Paso 10 - Verificar nuevamente

In [68]:
df.duplicated().sum()

np.int64(0)

Paso 11 - Revisar categorías

In [69]:
for columna in df.select_dtypes(include="object").columns:
    print("\n", columna)
    print(df[columna].value_counts())

 subscription_plan
subscription_plan
Básico       3394
Estándar     2669
Premium      1490
basico         60
BASICO         52
Basic          52
básico         50
Std            48
Estándar       46
estandar       36
STANDARD       34
Premium        31
PREMIUM        26
Premiun        23
premium        22
Name: count, dtype: int64

 country
country
Chile         1118
Brasil        1115
México        1106
Uruguay       1105
Colombia      1099
Perú          1095
Argentina     1075
colombia        27
méxico          25
uruguay         24
Brazil          21
COL             19
CHL             18
URY             17
argentina       16
MEX             16
Chile           16
PER             16
Peru            15
BRA             15
chile           15
Mexico          15
brasil          13
perú            12
ARG             10
Argentina       10
Name: count, dtype: int64

 favorite_genre
favorite_genre
Comedia        1334
Drama          1088
Thriller       1077
Romance        1070
Documental     1070
Acción         1066
Crime          1049
Action           22
COMEDIA          19
Crimen           18
Romance          17
CRIME            17
Documentary      16
DRAMA            16
Comedia          15
DOC              15
ROMANCE          14
ACCIÓN           14
THRILLER         14
comedy           12
Thriller         12
romance          12
documental       10
drama            10
accion            8
Drama             7
thriler           6
crime             5
Name: count, dtype: int64

 last_login_date
last_login_date
2026-15-03       340
0000-00-00        17
2029-01-01        15
not_available     14
31-02-2022        13
                ...
2018-11-07         1
2022-03-20         1
2019-01-19         1
2018-05-03         1
2024-02-12         1
Name: count, Length: 3062, dtype: int64

Paso 12 - Corregir planes

In [70]:
df["subscription_plan"] = df["subscription_plan"].replace({
    "basico": "Básico",
    "BASICO": "Básico",
    "Basic": "Básico",
    "básico": "Básico",

    "Std": "Estándar",
    "estandar": "Estándar",
    "STANDARD": "Estándar",
    "Estándar ": "Estándar",
    "Standard": "Estándar",

    "Premium ": "Premium",
    "PREMIUM": "Premium",
    "Premiun": "Premium",
    "premium": "Premium"
})

In [71]:
df["subscription_plan"].value_counts()

subscription_plan
Básico      3608
Estándar    2833
Premium     1592
Name: count, dtype: int64

Paso 13 - Corregir países

In [72]:
df["country"] = df["country"].str.strip()

df["country"] = df["country"].replace({

    "colombia": "Colombia",
    "COL": "Colombia",

    "méxico": "México",
    "Mexico": "México",
    "MEX": "México",

    "uruguay": "Uruguay",
    "URY": "Uruguay",

    "Brazil": "Brasil",
    "BRA": "Brasil",
    "brasil": "Brasil",

    "Peru": "Perú",
    "PER": "Perú",
    "perú": "Perú",

    "CHL": "Chile",
    "chile": "Chile",

    "argentina": "Argentina",
    "ARG": "Argentina"
})

In [73]:
df["country"].value_counts()

country
Chile        1167
Brasil       1164
México       1162
Uruguay      1146
Colombia     1145
Perú         1138
Argentina    1111
Name: count, dtype: int64

Paso 14 - Corregir géneros

In [74]:
df["favorite_genre"] = df["favorite_genre"].str.strip()

df["favorite_genre"] = df["favorite_genre"].replace({

    "Action": "Acción",
    "ACCIÓN": "Acción",
    "accion": "Acción",

    "Comedy": "Comedia",
    "COMEDIA": "Comedia",
    "comedy": "Comedia",
    "Comedia ": "Comedia",

    "Crime": "Crimen",
    "CRIME": "Crimen",
    "crime": "Crimen",

    "Documentary": "Documental",
    "DOC": "Documental",
    "documental": "Documental",

    "Drama": "Drama",
    "DRAMA": "Drama",
    "drama": "Drama",

    "ROMANCE": "Romance",
    "romance": "Romance",
    "Romance ": "Romance",

    "THRILLER": "Thriller",
    "Thriller ": "Thriller",
    "thriler": "Thriller"
})

In [75]:
df["favorite_genre"].value_counts()

favorite_genre
Comedia       1380
Drama         1121
Romance       1113
Documental    1111
Acción        1110
Thriller      1109
Crimen        1089
Name: count, dtype: int64

Paso 15 - Convertir fechas

In [76]:
df["last_login_date"] = df["last_login_date"].replace({

    "0000-00-00": pd.NA,
    "not_available": pd.NA,
    "2026-15-03": pd.NA,
    "31-02-2022": pd.NA,
    "2029-01-01": pd.NA

})

In [77]:
df["last_login_date"] = pd.to_datetime(
    df["last_login_date"],
    errors="coerce"
)

In [78]:
df["last_login_date"] = df["last_login_date"].fillna(
    df["last_login_date"].mode()[0]
)

Paso 16 - Pasarlas al formato AAAA-MM-DD (2000-10-20)

In [79]:
df["last_login_date"] = df["last_login_date"].dt.strftime("%Y-%m-%d")

Paso 17 - Revisar edades

In [80]:
df["age"].describe()

count    8033.000000
mean       34.102452
std        14.564489
min        -5.000000
25%        25.000000
50%        33.000000
75%        42.000000
max       150.000000
Name: age, dtype: float64

Paso 18 - Corregir edades fuera de rango

In [81]:
mediana = df["age"].median()

df.loc[df["age"] < 13, "age"] = mediana
df.loc[df["age"] > 100, "age"] = mediana

Paso 19 - Revisar tiempo de visualización

In [82]:
df["monthly_watch_time_mins"].describe()

count     8033.000000
mean      1103.360612
std       5288.513174
min       -120.000000
25%        493.800000
50%        757.400000
75%       1035.600000
max      99999.000000
Name: monthly_watch_time_mins, dtype: float64

Paso 20 - Corregir tiempos negativos

In [83]:
mediana = df["monthly_watch_time_mins"].median()

df.loc[df["monthly_watch_time_mins"] < 0,
       "monthly_watch_time_mins"] = mediana

Paso 21 - Revisar tickets de soporte

In [84]:
df["customer_support_tickets"].describe()

count    8033.000000
mean        1.817129
std        11.422986
min        -1.000000
25%         0.000000
50%         1.000000
75%         1.000000
max       150.000000
Name: customer_support_tickets, dtype: float64

Paso 22 - Verificación final

In [91]:
print(df.isnull().sum())

print(df.duplicated().sum())

print(df.shape)

user_id                     0
age                         0
subscription_plan           0
monthly_watch_time_mins     0
country                     0
favorite_genre              0
last_login_date             0
customer_support_tickets    0
dtype: int64
0
(8022, 8)

Paso 23 - Guardar el dataset limpio

In [93]:
df.to_json(
    "streaming_users_clean.json",
    orient="records",
    indent=4
)

Paso 24 - Descargar el dataset

In [94]:
from google.colab import files

files.download("streaming_users_clean.json")

In [ ]:
# Conclusión

En esta etapa revisé la calidad del conjunto de datos y fui corrigiendo los problemas que encontré antes de comenzar el análisis. Se completaron los valores faltantes, se eliminaron los registros duplicados y se unificaron las categorías que estaban escritas de diferentes maneras, como los planes de suscripción, los países y los géneros favoritos. También se corrigieron fechas con formatos incorrectos y algunos valores que podían generar errores en el análisis.

Gracias a estas modificaciones, el dataset quedó mucho más ordenado y consistente, lo que permite trabajar con información más confiable en las siguientes etapas del proyecto. Además, el archivo original se mantuvo sin modificaciones y se generó una versión limpia para utilizar en el análisis exploratorio y en el resto del trabajo.